#!/usr/bin/env node
// build-catalog.mjs: writes plugins/stable-build/skills/guide/references/catalog.md
// from the frontmatter of every SKILL.md in plugins/stable-build/skills/.
//
// The catalog is generated so the guide skill never carries hand-kept lists or counts.
// Output is deterministic (no timestamps), so `--check` can detect a stale catalog in CI.
//
// Usage: node tools/build-catalog.mjs [--check] [--stdout] [--root DIR]

import { readFileSync, writeFileSync, mkdirSync, existsSync, renameSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { REPO_ROOT, findSkills } from './check-names.mjs';

export const PLUGIN = 'stable-build';
export const CATALOG_REL = 'plugins/stable-build/skills/guide/references/catalog.md';

// Display groups. A skill missing here still appears, under "Other skills".
const GROUPS = [
  { title: 'Start here', skills: ['guide'] },
  { title: 'Builder journey', skills: ['find-idea', 'new-app', 'gotchas', 'go-live', 'studio-delegate'] },
  { title: 'Roles', skills: ['analyst', 'pm', 'ux-designer', 'architect', 'dev', 'tech-writer'] },
  { title: 'Shared workflows', skills: ['product-brief', 'architecture', 'stories', 'layered-review'] },
];

const cell = (s) => String(s ?? '').replace(/\s+/g, ' ').trim().replace(/\|/g, '\\|');

export function buildCatalog(root = REPO_ROOT) {
  const skills = findSkills(root).filter((s) => s.plugin === PLUGIN && s.fm.data.name);
  const byName = new Map(skills.map((s) => [s.fm.data.name, s]));
  const used = new Set();
  const sections = [];
  for (const g of GROUPS) {
    const rows = g.skills.filter((n) => byName.has(n));
    rows.forEach((n) => used.add(n));
    if (rows.length) sections.push({ title: g.title, rows });
  }
  const rest = [...byName.keys()].filter((n) => !used.has(n)).sort();
  if (rest.length) sections.push({ title: 'Other skills', rows: rest });

  const out = [];
  out.push('<!-- GENERATED by tools/build-catalog.mjs from SKILL.md frontmatter. Do not edit by hand. -->');
  out.push('<!-- Regenerate with: node tools/build-catalog.mjs -->');
  out.push('');
  out.push('# stable-build skill catalog');
  out.push('');
  out.push('Every skill in the stable-build plugin, taken from its frontmatter.');
  out.push('In Claude Code, invoke a skill as `/stable-build:<name>`.');
  out.push('In Codex, pick it by name; plugin skills are namespaced under `stable-build`.');
  out.push("Circle's skills (for example `use-usdc` or `bridge-stablecoin`) come from Circle's own plugin and are not listed here.");
  for (const sec of sections) {
    out.push('');
    out.push(`## ${sec.title}`);
    out.push('');
    out.push('| Skill | Use it when |');
    out.push('|---|---|');
    for (const n of sec.rows) out.push(`| \`${cell(n)}\` | ${cell(byName.get(n).fm.data.description)} |`);
  }
  out.push('');
  return out.join('\n');
}

function main(argv) {
  let check = false; let stdout = false; let root = REPO_ROOT;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') check = true;
    else if (a === '--stdout') stdout = true;
    else if (a === '--root') root = resolve(argv[++i] ?? '.');
    else if (a.startsWith('--root=')) root = resolve(a.slice(7));
    else if (a === '-h' || a === '--help') { console.log('usage: node tools/build-catalog.mjs [--check] [--stdout] [--root DIR]'); return 0; }
    else { console.error(`build-catalog: unknown argument ${a}`); return 2; }
  }
  const text = buildCatalog(root);
  const target = join(root, CATALOG_REL);
  if (stdout) { process.stdout.write(text); return 0; }
  if (check) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : null;
    if (current === text) { console.log(`build-catalog: ${CATALOG_REL} is up to date`); return 0; }
    console.error(`build-catalog: ${CATALOG_REL} is ${current === null ? 'missing' : 'stale'}; run: node tools/build-catalog.mjs`);
    return 1;
  }
  if (!existsSync(join(root, 'plugins', PLUGIN, 'skills', 'guide'))) {
    console.error('build-catalog: plugins/stable-build/skills/guide does not exist; nothing written');
    return 1;
  }
  mkdirSync(dirname(target), { recursive: true });
  const tmp = `${target}.tmp-${process.pid}`;
  writeFileSync(tmp, text);
  renameSync(tmp, target);
  console.log(`build-catalog: wrote ${CATALOG_REL}`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  process.exitCode = main(process.argv.slice(2));
}
